### ISSUE TITLE
Videos page - pagination

### ISSUE THREAD

**Issue by asidelnik** [asidelnik/documentor#47]
### Tasks
- [x] [Implement MUI Controlled pagination](https://mui.com/material-ui/react-pagination/#controlled-pagination)
- [x] Test that when the data is filtered, query mutations (status & event) update the pagination
  - [x] Bug - mutating videos by status, doesn't call videos count mutation
  - [x] Solution - call both queries in separate invalidateQueries
- [ ] **Rename AllVideosPage to VideosPage**

### Testing - VideosPage - add/edit
- [x] On filter updates
  - [x] Return the pagination to the first page
  - [x] In subroute "add-videos-to-event", unselect all.
  - [ ] #149 
- [x] "add-videos-to-event" sub route
  - [x] Pagination - add videos to event - made default "items per page" 25 instead of 5. To view & select more items for adding.
  - [x] Pagination - on page change or per page change - keep selected videos

### Notes
A dashboard/backoffice system should be finite and understandable.
It's better to use pagination than infinite scroll.
https://github.com/TanStack/query/discussions/3360
